Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 400
  LogSavePath: storage/logs/app.log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .gif

Database:
  DBType: mysql
  UserName: root
  PassWord: 123456
  Host: 127.0.0.1:3306
  DBName: blog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

JWT:
  Secret: love190613
  Isssuser: ~.~小明同学
  Expire: 7200